"$schema" = 'https://starship.rs/config-schema.json'

#-------------------------------------------------------------------
# Format

format = """
$os\
$username\
[](bg:background fg:red)\
[ ](bg:background)\
[](bg:background fg:yellow)\
$directory\
[](bg:background fg:yellow)\
[ ](bg:background)\
[](bg:background fg:green)\
$git_branch\
$git_status\
[](bg:background fg:green)\
[ ](bg:background)\
[](bg:background fg:cyan)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
[](bg:background fg:cyan)\
[ ](bg:background)\
[](bg:background fg:blue)\
$docker_context\
[](bg:background fg:blue)\
[ ](bg:background)\
$fill\
[ ](bg:background)\
$cmd_duration\
[](bg:background fg:magenta)\
$time\
$line_break$character"""

#-------------------------------------------------------------------
# Colors

palette = 'tokyo-night'

[palettes.ayu-iceberg]
text = "#bfbdb6"
background = "#0b0e14"

black = "#1e2132" 
white = "#c6c8d1"

red = "#e27878"
yellow = "#e2a478"
green = "#b4be82"
cyan = "#89b8c2"
blue = "#84a0c6"
magenta = "#a093c7"

[palettes.tokyo-night]
text = "#a9b1d6"
background = "#1a1b26"

black = "#414868" 
white = "#c0caf5"

red = "#f7768e"
yellow = "#e0af68"
green = "#73daca"
cyan = "#7dcfff"
blue = "#7aa2f7"
magenta = "#bb9af7"

#-------------------------------------------------------------------
#Data

[username]
format = '(fg:current_line)[  $user ](fg:black bg:red)'
show_always = true
style_user = "bg:red fg:black"
style_root = "bg:red fg:black"


[directory]
style = "fg:black bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"


[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:black bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:black bg:green)]($style)'


[nodejs]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[c]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[rust]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[golang]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[php]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[java]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[kotlin]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[haskell]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[python]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'


[docker_context]
disabled = false
symbol = ""
style = "bg:black"
format = '[[ $symbol( $context) ](fg:#black bg:blue)]($style)'


[fill]
symbol = ''
style = 'white'


[cmd_duration]
min_time = 500
style = 'fg:magenta'
format = ' [$duration]($style) '


[time]
disabled = false
time_format = "%R"
style = "bg:magenta"
format = '[[ $time  ](fg:black bg:magenta)]($style)'


[line_break]
disabled = false


[character]
#format = """[╰─$symbol](fg:white) """
disabled = false
success_symbol = '[ ❯](bold fg:green)'
error_symbol = '[ ❯](bold fg:red)'
vimcmd_symbol = '[ ❮](bold fg:green)'
vimcmd_replace_one_symbol = '[ ❮](bold fg:purple)'
vimcmd_replace_symbol = '[ ❮](bold fg:purple)'
vimcmd_visual_symbol = '[ ❮](bold fg:lavender)'
