font_family Hasklug Nerd Font Mono
font_size 10
background_opacity 0.95

background #0b0e14
foreground #bfbdb6

selection_background #1b3a5b
selection_foreground #bfbdb6

cursor #bfbdb6

# COLORS
# black
color0 #161821

# red
color1 #e27878

# green
color2 #b4be82

# yellow/orange
color3 #e2a478

# blue
color4 #84a0c6

# magenta/purple
color5 #a093c7

# cyan
color6 #89b8c2

# white
color7 #c6c8d1


# tab bar
active_tab_foreground   #161821
active_tab_background   #84a0c6
inactive_tab_foreground #d2d4de
inactive_tab_background #353a50
tab_bar_background      #0f1117